NewSocialNetwork/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using NewSocialNetwork.Data;
using NewSocialNetwork.Models;
using NewSocialNetwork.ViewModels;

namespace NewSocialNetwork.Controllers
{
    public class HomeController : Controller
    {
        UserManager<User> _userManager;
        ApplicationContext _context;
        IHostingEnvironment _appEnvironment;

        public HomeController(UserManager<User> userManager, ApplicationContext context, IHostingEnvironment appEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _appEnvironment = appEnvironment;
        }

        public async Task<IActionResult> Index() // Стартовая страница приложения (Профиль пользователя)
        {
            if (User.Identity.IsAuthenticated)
            {
                User user = await _userManager.FindByNameAsync(User.Identity.Name);
                return View(user);
            }
            return View();
        }

        [Authorize(Roles = "admin, user")]
        public IActionResult MessageList()
        {
            ViewData["Message"] = "Your messages.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

NewSocialNetwork/Controllers/ProfileSettingsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NewSocialNetwork.Data;
using NewSocialNetwork.Models;
using NewSocialNetwork.ViewModels;

namespace NewSocialNetwork.Controllers
{

    public class ProfileSettingsController : Controller
    {
        UserManager<User> _userManager;
        ApplicationContext _context;
        IHostingEnvironment _appEnvironment;

        public ProfileSettingsController(UserManager<User> userManager, ApplicationContext context, IHostingEnvironment appEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _appEnvironment = appEnvironment;
        }

        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> EditProfile() // Страница настроек пользователя
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            if (user == null)
            {
                return NotFound();
            }
            AdditionalSettingsViewModel model = new AdditionalSettingsViewModel
            {
                Name = user.Name,
                Surname = user.Surname,
                Country = user.Country,
                Email = user.Email,
                Birthday = user.Birthday,

                Activities = user.Activities,
                FavoriteFilms = user.FavoriteFilms,
                FavoriteGames = user.FavoriteGames,
                Interests = user.Interests,
                Languages = user.Languages
            };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> EditProfile(AdditionalSettingsViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByNameAsync(User.Identity.Name);

                user.Name = model?.Name;
                user.Surname = model?.Surname;
                user.Country = model?.Country;
                user.Email = model?.Email;
                user.Birthday = model.Birthday;

                user.Activities = model?.Activities;
                user.FavoriteFilms = model?.FavoriteFilms;
                user.FavoriteGames = model?.FavoriteGames;
                user.Interests = model?.Interests;
                user.Languages = model?.Languages;

                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> AddPhoto(IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                User user = await _userManager.FindByNameAsync(User.Identity.Name);

                if (user.ImagePath != null) // Если фото уже существует удаляем его 
                {
                    FileInfo fileInf = new FileInfo(user.ImagePath);
                    if (fileInf.Exists)
                    {
                        fileInf.Delete();
                    }
                }

                string path = "/Photos/" + uploadedFile.FileName; // путь к папке Files
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
                user.ImagePath = path;
                user.ImageName = uploadedFile.FileName;
                _context.SaveChanges();
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

NewSocialNetwork/Views/Home/EditProfile.cshtml
@model NewSocialNetwork.Models.User

<h3>Upload photo</h3>

<form asp-action="AddPhoto" asp-controller="Home" method="post" enctype="multipart/form-data">
    <input type="file" accept="image/*" name="uploadedFile" /><br>
    <input type="submit" value="Set photo" class="btn btn-default" />
</form>

<br>
<br>

<form asp-action="EditMainInfo" asp-controller="Home" method="post">
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="email" asp-for="Email" class="form-control" />
        <span asp-validation-for="Email"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label">Name</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Surname" class="control-label">Surname</label>
        <input type="text" asp-for="Surname" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Birthday" class="control-label">Birthday</label>
        <input type="date" asp-for="Birthday" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Country" class="control-label">Country</label>
        <input type="text" asp-for="Country" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-default" />
    </div>
</form>

<br>
<br>

<form asp-action="EditProfile" asp-controller="Home" method="post">
    <div class="form-group">
        <label asp-for="Languages" class="control-label">Languages</label>
        <input type="text" asp-for="Languages" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Interests" class="control-label">Interests</label>
        <input type="text" asp-for="Interests" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="FavoriteGames" class="control-label">FavoriteGames</label>
        <input type="text" asp-for="FavoriteGames" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="FavoriteFilms" class="control-label">FavoriteFilms</label>
        <input type="text" asp-for="FavoriteFilms" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Activities" class="control-label">Activities</label>
        <input type="text" asp-for="Activities" class="form-control" />
    </div>
    <input type="submit" value="Enter" class="btn btn-default" />
</form>

NewSocialNetwork/Views/Home/FindFriends.cshtml
<h2> Search new Friends </h2>

<table class="table">
    <tr><th>Email</th><th>Birthday</th><th></th></tr>
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Email</td>
            <td>@user.Name</td>
            <td>@user.Surname</td>
            <td>@user.Country</td>
            <td>@user.Birthday</td>
            <td>
                    <a class="btn btn-sm btn-primary" asp-controller="Home" asp-action="AddFrend" asp-route-id="@user.Id">Add friend</a>
            </td>
        </tr>
    }
</table>

NewSocialNetwork/Views/Home/FriendList.cshtml
@model NewSocialNetwork.Models.User

<h2>Your friends</h2>

<br>
<a class="btn btn-sm btn-primary" asp-area="" asp-controller="Home" asp-action="FindFriends">Find new friend</a>
<br>

@if (Model.Friends != null)
{

    @foreach (var item in Model.Friends)
    {
        <def>
            <h4>@item.Name @item.Surname</h4>
            <p>@item.UserName</p>
            <img src=@item.ImagePath alt="User photo" width="300" height="250" />
        </def>
    }

}
else
{
        <h4> Friends list is empty </h4>
}

NewSocialNetwork/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model NewSocialNetwork.Models.User

@if (User.Identity.IsAuthenticated)
{
    <h2>@Model.Name @Model.Surname</h2>

    <img src=@Model.ImagePath alt="User photo" width="300" height="250" />

    <p>@Model.UserName</p>
    <p>@Localizer["Country"] :  @Model.Country</p>
    <p>@Localizer["Birthday"] :  @Model.Birthday</p>
    <details>
        <summary>@Localizer["info"] <a asp-area="" asp-controller="ProfileSettings" asp-action="EditProfile">@Localizer["Edit"]</a></summary>
        <ul>
            <li>@Localizer["Languages"] :  @Model.Languages</li>
            <li>@Localizer["Interests"] :  @Model.Interests</li>
            <li>@Localizer["Favorites Games"] :  @Model.FavoriteGames</li>
            <li>@Localizer["Favorites Films"] :  @Model.FavoriteFilms</li>
            <li>@Localizer["Activities"] :  @Model.Activities</li>
        </ul>
    </details>
}
else
{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Oswald'>
    <link rel="stylesheet" href="~/invitation/css/style.css">
    <div class="text">@Localizer["message"]</div>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
    <script src="~/invitation/js/index.js"></script>
}

NewSocialNetwork/Views/Home/MessageList.cshtml
<h2>Messages</h2>