NewSocialNetwork/Components/FollowersViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NewSocialNetwork.Data;
using NewSocialNetwork.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewSocialNetwork.Components
{
    public class FollowersViewComponent : ViewComponent
    {
        private UserManager<User> _userManager;
        private ApplicationContext _context;

        public FollowersViewComponent(UserManager<User> userManager, ApplicationContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);  
            return View(_context.Follows.Where(var => var.FollowingId == user.Id).Select(var => var.Follower).ToList());
        }
    }
}

NewSocialNetwork/Components/FollowingViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NewSocialNetwork.Data;
using NewSocialNetwork.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewSocialNetwork.Components
{
    public class FollowingViewComponent : ViewComponent
    {
        private UserManager<User> _userManager;
        ApplicationContext _context;

        public FollowingViewComponent(UserManager<User> userManager, ApplicationContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            return View(_context.Follows.Where(var => var.FollowerId == user.Id).Select(var => var.Following).ToList());
        }
    }
}

NewSocialNetwork/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NewSocialNetwork.Data;
using NewSocialNetwork.Models;

namespace NewSocialNetwork.Controllers
{
    public class FriendController : Controller
    {
        const int friendCount = 3;
        UserManager<User> _userManager;
        ApplicationContext _context;
        IHostingEnvironment _appEnvironment;

        public FriendController(UserManager<User> userManager, ApplicationContext context, IHostingEnvironment appEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _appEnvironment = appEnvironment;
        }

        [HttpGet]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> FriendList(int pageNumber = 0)
        {
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("~/Views/Shared/_Friend.cshtml", await getFriendList(pageNumber));
                //return View(userFollower.Intersect(userFollowing).Skip(pageNumber * friendCount).Take(friendCount).ToList());
            }
            else return View(await getFriendList(pageNumber));
            //return View(userFollower.Intersect(userFollowing).ToList());
        }

        private async Task<List<User>> getFriendList(int pageNumber)
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            // Подписчики на user 
            var userFollower = _context.Follows.Where(var => var.FollowingId == user.Id).Select(var => var.Follower);
            // Подписки user
            var userFollowing = _context.Follows.Where(var => var.FollowerId == user.Id).Select(var => var.Following);
            return userFollower.Intersect(userFollowing).Skip(pageNumber * friendCount).Take(friendCount).ToList();
        }

        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> FindFriends()
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            var allUser = _userManager.Users.ToList();
            // Подписки user
            var userFollowing = _context.Follows.Where(var => var.FollowerId == user.Id).Select(var => var.Following);
            var result = allUser.Except(userFollowing).ToList();
            result.Remove(user);
            return View(result);
        }

        [HttpGet]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> AddFriend(string id)
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            User friend = await _userManager.FindByIdAsync(id);
            
            if (friend != null && user != null)
            {
                if (user.Followings == null)
                    user.Followings = new List<Follow>();
                if (friend.Followers == null)
                    friend.Followers = new List<Follow>();
                var follow = new Follow(user, friend);
                _context.Follows.Add(follow);
                _context.Users.Find(user.Id).Followings.Add(follow);
                _context.Users.Find(friend.Id).Followers.Add(follow);

                var result1 = await _userManager.UpdateAsync(user);
                var result2 = await _userManager.UpdateAsync(friend);
                if (result1.Succeeded && result2.Succeeded)
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction("FindFriends");
                }
                else
                {
                    return NotFound();
                }
            }
            else return NotFound();
        }

        [HttpGet]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> DeleteFriend(string id)
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            User friend = await _userManager.FindByIdAsync(id);

            if (friend != null && user != null)
            {
                var follow = _context.Follows.Where(t =>t.FollowerId == user.Id && t.FollowingId == friend.Id).ToList();
                _context.Follows.Remove(follow[0]);
                _context.Users.Find(user.Id).Followings.Remove(follow[0]);
                _context.Users.Find(friend.Id).Followers.Remove(follow[0]);

                var result1 = await _userManager.UpdateAsync(user);
                var result2 = await _userManager.UpdateAsync(friend);
                if (result1.Succeeded && result2.Succeeded)
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction("FriendList");
                }
                else
                {
                    return NotFound();
                }
            }
            else return NotFound();
        }

        [Route("Followers")]
        [Route("FollowersList")]
        [Authorize(Roles = "admin, user")]
        public IActionResult FollowersList() { return View(); }

        [Route("Following")]
        [Route("FollowingList")]
        [Authorize(Roles = "admin, user")]
        public IActionResult FollowingList() { return View(); }
    }
}

NewSocialNetwork/Views/Friend/FindFriends.cshtml
<h2 class="text-center"> Search new Friends </h2>

@foreach (User user in Model)
{
        @await Html.PartialAsync("_UserTemplate", user)
        <hr />
}

NewSocialNetwork/Views/Friend/FollowersList.cshtml
@await Component.InvokeAsync("Followers")

NewSocialNetwork/Views/Friend/FollowingList.cshtml
@await Component.InvokeAsync("Following")

NewSocialNetwork/Views/Friend/FriendList.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model List<User>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<h2 class="text-center">@Localizer["message"]</h2>

<br>
<div class="text-center">
    <a class="btn btn-sm btn-primary" asp-area="" asp-controller="Friend" asp-action="FindFriends">@Localizer["Find"]</a>
</div>
<br>

@if (Model != null && Model.Count != 0)
{
    <div class="posts" id="postsArea">
        @{await Html.RenderPartialAsync("_Friend", Model);}
    </div>
}
else
{
    <h4 class="text-center"> @Localizer["empty"] </h4>
}

<script>
    $(function () {
        var pageNumber = 0;
        var _inCallback = false;
        function getUsers() {
            if (pageNumber > -1 && !_inCallback) {
                _inCallback = true;
                pageNumber++;
                $.ajax({
                    type: 'GET',
                    url: '/Friend/FriendList',
                    data: { pageNumber },
                    success: function (data) {
                        if (data != '') {
                            $(".posts").append(data);
                        }
                        else {
                            pageNumber = -1;
                        }
                        _inCallback = false;
                    }
                });
            }
        }
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() > $(document).height() - 50) {
                getUsers();
            }
        });
    })
</script>