NewSocialNetwork/Controllers/ChatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NewSocialNetwork.Data;
using NewSocialNetwork.Models;

namespace NewSocialNetwork.Controllers
{
    public class ChatsController : Controller
    {
        UserManager<User> _userManager;
        ApplicationContext _context;
        IHostingEnvironment _appEnvironment;
        User SelectedUser;

        public ChatsController(UserManager<User> userManager, ApplicationContext context, IHostingEnvironment appEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _appEnvironment = appEnvironment;
        }

        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> SelectedChat(string id)
        {
            if (id != null)
            {
                var Recipient = await _userManager.FindByIdAsync(id);
                var Sender = await _userManager.FindByNameAsync(User.Identity.Name);
                SelectedUser = Recipient;
                return View(new List<User> { Recipient, Sender });
            }
            else return NotFound();
        }

        //[Authorize(Roles = "admin, user")]
        //public IActionResult getData()
        //{
        //    if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
        //    {
        //        return View(SelectedUser.UserName);
        //    }
        //    return NotFound();
        //}

        [Authorize(Roles = "admin, user")]
        public IActionResult getMessage(string massage, string userName)
        {
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("~/Views/Shared/_Message.cshtml", (userName, massage));
            }
            return NotFound();
        }
    }
}

NewSocialNetwork/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NewSocialNetwork.Data;
using NewSocialNetwork.Models;

namespace NewSocialNetwork.Controllers
{
    public class FriendController : Controller
    {
        const int friendCount = 3;
        UserManager<User> _userManager;
        ApplicationContext _context;
        IHostingEnvironment _appEnvironment;

        public FriendController(UserManager<User> userManager, ApplicationContext context, IHostingEnvironment appEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _appEnvironment = appEnvironment;
        }

        [HttpGet]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> FriendList(int pageNumber = 0)
        {
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("~/Views/Shared/_Friend.cshtml", await getFriendList(pageNumber));
                //return View(userFollower.Intersect(userFollowing).Skip(pageNumber * friendCount).Take(friendCount).ToList());
            }
            else return View(await getFriendList(pageNumber));
            //return View(userFollower.Intersect(userFollowing).ToList());
        }

        private async Task<List<User>> getFriendList(int pageNumber)
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            // Подписчики на user 
            var userFollower = _context.Follows.Where(var => var.FollowingId == user.Id).Select(var => var.Follower);
            // Подписки user
            var userFollowing = _context.Follows.Where(var => var.FollowerId == user.Id).Select(var => var.Following);
            return userFollower.Intersect(userFollowing).Skip(pageNumber * friendCount).Take(friendCount).ToList();
        }

        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> FindFriends()
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            var allUser = _userManager.Users.ToList();
            // Подписки user
            var userFollowing = _context.Follows.Where(var => var.FollowerId == user.Id).Select(var => var.Following);
            var result = allUser.Except(userFollowing).ToList();
            result.Remove(user);
            return View(result);
        }

        [HttpGet]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> AddFriend(string id)
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            User friend = await _userManager.FindByIdAsync(id);
            
            if (friend != null && user != null)
            {
                if (user.Followings == null)
                    user.Followings = new List<Follow>();
                if (friend.Followers == null)
                    friend.Followers = new List<Follow>();
                var follow = new Follow(user, friend);
                _context.Follows.Add(follow);
                _context.Users.Find(user.Id).Followings.Add(follow);
                _context.Users.Find(friend.Id).Followers.Add(follow);

                var result1 = await _userManager.UpdateAsync(user);
                var result2 = await _userManager.UpdateAsync(friend);
                if (result1.Succeeded && result2.Succeeded)
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction("FindFriends");
                }
                else
                {
                    return NotFound();
                }
            }
            else return NotFound();
        }

        [HttpGet]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> DeleteFriend(string id)
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            User friend = await _userManager.FindByIdAsync(id);

            if (friend != null && user != null)
            {
                var follow = _context.Follows.Where(t =>t.FollowerId == user.Id && t.FollowingId == friend.Id).ToList();
                _context.Follows.Remove(follow[0]);
                _context.Users.Find(user.Id).Followings.Remove(follow[0]);
                _context.Users.Find(friend.Id).Followers.Remove(follow[0]);

                var result1 = await _userManager.UpdateAsync(user);
                var result2 = await _userManager.UpdateAsync(friend);
                if (result1.Succeeded && result2.Succeeded)
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction("FriendList");
                }
                else
                {
                    return NotFound();
                }
            }
            else return NotFound();
        }

        [Route("Followers")]
        [Route("FollowersList")]
        [Authorize(Roles = "admin, user")]
        public IActionResult FollowersList() { return View(); }

        [Route("Following")]
        [Route("FollowingList")]
        [Authorize(Roles = "admin, user")]
        public IActionResult FollowingList() { return View(); }
    }
}

NewSocialNetwork/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NewSocialNetwork.Models;
using NewSocialNetwork.ViewModels;

namespace NewSocialNetwork.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        SignInManager<User> _signInManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);
                await _userManager.RemoveFromRolesAsync(user, removedRoles);
                await _userManager.UpdateSecurityStampAsync(user);
                return RedirectToAction("Index");
            }

            return NotFound();
        }
    }
}

NewSocialNetwork/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NewSocialNetwork.Models;
using NewSocialNetwork.ViewModels;

namespace NewSocialNetwork.Controllers
{
    public class UsersController : Controller
    {
        UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        [Authorize(Roles = "admin")]
        public IActionResult Index() => View(_userManager.Users.ToList());

        [Authorize(Roles = "admin")]
        public IActionResult Create() => View();

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User
                {
                    Email = model.Email,
                    UserName = model.Email,
                    Birthday = model.Birthday,
                    Country = model.Country,
                    Name = model.Name,
                    Surname = model.Surname
                };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                Birthday = user.Birthday,
                Country = user.Country,
                Name = user.Name,
                Surname = user.Surname
            };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.Birthday = model.Birthday;
                    user.Country = model.Country;
                    user.Name = model.Name;
                    user.Surname = model.Surname;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    var _passwordValidator =
                        HttpContext.RequestServices.GetService(typeof(IPasswordValidator<User>)) as IPasswordValidator<User>;
                    var _passwordHasher =
                        HttpContext.RequestServices.GetService(typeof(IPasswordHasher<User>)) as IPasswordHasher<User>;

                    IdentityResult result =
                        await _passwordValidator.ValidateAsync(_userManager, user, model.NewPassword);
                    if (result.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, model.NewPassword);
                        await _userManager.UpdateAsync(user);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "User is not found");
                }
            }
            return View(model);
        }
    }
}

NewSocialNetwork/Views/Shared/_Follower.cshtml
@model User

<div style="margin: auto auto auto auto;">
    <div class="center-block">
        <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="350" height="350" src=@Model.ImagePath alt="User photo" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#55595c"></rect></img>
            <div class="card-body">
                <p class="card-text">
                    <b>@Model.Name @Model.Surname</b> <br />
                    @Model.Email
                </p>
                <small class="text-muted">@Model.Country</small>
            </div>
        </div>
    </div>
</div>

NewSocialNetwork/Views/Shared/_Following.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model User

<div style="margin: auto auto auto auto;">
    <div class="center-block">
        <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="350" height="350" src=@Model.ImagePath alt="User photo" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#55595c"></rect></img>
            <div class="card-body">
                <p class="card-text">
                    <b>@Model.Name @Model.Surname</b> <br />
                    @Model.Email
                </p>
                <div class="btn-group">
                    <a class="btn-danger" asp-controller="Friend" asp-action="DeleteFriend" asp-route-id="@Model.Id">@Localizer["Delete"]</a>
                </div>
                <small class="text-muted">@Model.Country</small>
            </div>
        </div>
    </div>
</div>

NewSocialNetwork/Views/Shared/_Friend.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model List<User>

@foreach (User item in Model)
{
    <img class="bd-placeholder-img card-img-top" width="350" height="350" src=@item.ImagePath alt="User photo" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#55595c"></rect>
    <div class="card-body">
        <p class="card-text">
            <b>@item.Name @item.Surname</b> <br />
            @item.Email
        </p>
        <div class="btn-group">
            <a class="btn btn-sm btn-danger" asp-controller="Friend" asp-action="DeleteFriend" asp-route-id="@item.Id">@Localizer["Delete"]</a>
            <a class="btn btn-sm btn-primary" asp-controller="Chats" asp-action="SelectedChat" asp-route-id="@item.Id">@Localizer["Message"]</a>
        </div>
        <small class="text-muted">@item.Country</small>
    </div>
}

NewSocialNetwork/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NewSocialNetwork</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Oswald'>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">NewSocialNetwork</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a></li>
                    <li><a asp-area="" asp-controller="Friend" asp-action="FollowersList">@Localizer["Followers"]</a></li>
                    <li><a asp-area="" asp-controller="Friend" asp-action="FollowingList">@Localizer["Following"]</a></li>
                    <li><a asp-area="" asp-controller="Friend" asp-action="FriendList">@Localizer["Friends"]</a></li>
                    @*<li><a asp-area="" asp-controller="Home" asp-action="MessageList">Messages</a></li>*@
                    <partial name="_LoginPartial" />
                    @if (User.IsInRole("admin"))
                    {
                        <li><a asp-area="" asp-controller="Users" asp-action="Index">@Localizer["Users"]</a></li>
                        <li>
                            <a asp-area="" asp-controller="Roles" asp-action="Index">
                                @Localizer["Roles"]
                            </a>
                        </li>
                    }
                    <li>
                        @await Html.PartialAsync("_SelectLanguagePartial")
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        @if (User.Identity.IsAuthenticated)
        {
            <footer>
                <date></date>
                <p>&copy; 2019 - NewSocialNetwork</p>
            </footer>
        }
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)

</body>
</html>

NewSocialNetwork/Views/Shared/_Message.cshtml
@model ValueTuple<string, string>

<p class="card-text">
    <b>@Model.Item1</b> <br />
    @Model.Item2
</p>

NewSocialNetwork/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    // получаем сервис IRequestCultureFeature
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    // получаем список поддерживаемых культур
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<form asp-controller="Home" asp-action="SetLanguage" style="margin-top:12px;"
      asp-route-returnUrl="@Context.Request.Path"
      method="post" class="form-horizontal">
    @Localizer["Language"] <select name="culture" onchange="this.form.submit();"
                                    asp-for="@requestCulture.RequestCulture.UICulture.Name"
                                    asp-items="cultureItems"></select>
</form>

NewSocialNetwork/Views/Shared/_UserTemplate.cshtml
@model User

<div style="margin: auto auto auto auto;">
    <div class="center-block">
        <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="350" height="350" src=@Model.ImagePath alt="User photo" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#55595c"></rect></img>
            <div class="card-body">
                <p class="card-text">
                    <b>@Model.Name @Model.Surname</b> <br />
                    @Model.Email
                </p>
                <div class="btn-group">
                    <a class="btn btn-sm btn-primary" asp-controller="Friend" asp-action="AddFriend" asp-route-id="@Model.Id">Add friend</a>
                </div>
                <small class="text-muted">@Model.Country</small>
            </div>
        </div>
    </div>
</div>